name: Nuclei - Vulnerability Scan

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: http://testphp.vulnweb.com/
          flags: "-severity critical,high,medium,low -stats"
